version: '3'

services:

#   db:
#     image: mip2
#     #build: ./psdi
#     ports:
#         - 5431:5432
#     volumes:
#         - c:\users\cforc\onedrive\pylearning\mienvf\psdi:/code
#         - pdv2:/var/lib/postgresql/data
    
 #backup:
  #  image: mipbackup
   # ports: 
   #       - 5439:5432
    #volumes:
    #    - pdv:/var/lib/postgresql/data
    
  web:
    #image: mipython
    build: . 
    command: >
      sh -c  "python manage.py makemigrations &&
              python manage.py migrate &&
              python3 manage.py runserver_plus 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8081:8000"
    # depends_on:
    #   - db

volumes:
  pdv2: